import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Component from "../components/Component";


const Home: NextPage = () => {  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Folio AI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.appheader}>
          Folio AI
      </header>

      <div className={styles.componentContainer}>
        <Component />
      </div>

    </div>
  )
}

export default Home
